### ISSUE TITLE
lokal html fil 

### ISSUE THREAD

**Issue by VegardBH2** [edvas/edvas.github.io#2]
Hvis du åpner html filen lokalt mangler bakrunnen og oppbygningen

**Comment by edvas** [comment]
Har du filen 'style.css' lokalt

**Comment by VegardBH2** [comment]
ja

**Comment by VegardBH2** [comment]
åpnet style.css og så åpnet jeg index.html så fikset den seg

**Comment by edvas** [comment]
Du måtte sikkert pakke ut zip-filen
