### ISSUE TITLE
Utforming av programmer

### ISSUE THREAD

**Issue by VegardBH2** [edvas/edvas.github.io#3]
![image](https://user-images.githubusercontent.com/45264938/48910041-3acb9080-ee6f-11e8-81dc-96a340936729.png)

**Comment by edvas** [comment]
Prøv å sette en konstant høyde (f.eks 18em, altså samme som teksten) og lag 'div' grupper med hver bokstav sammen med tilsvarende indatafelt, la hoved-'div'en ha 'display:flex;' og under-'div'ene være flex-kolloner. Tilslutt bruk 'overflow-x:hidden;' på indatafeltene

**Comment by VegardBH2** [comment]
![image](https://user-images.githubusercontent.com/45264938/48912466-ff809000-ee75-11e8-8a03-0f0dc763cc99.png)
Endrer main style fra 900 til 1060px, så passer alt

**Comment by edvas** [comment]
main/programmer skal egentlig ta 50% av bredden av skjermen (50vw ikke 1060px)

**Comment by edvas** [comment]
Ikke lenger relevant etter 'new-design'
